### ISSUE TITLE
Partners database failed to spin up

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/demos.haus#13]
https://jenkins.canonical.com/webteam/view/demos/job/start-demo/413/console

**Comment by jpmartinspt** [comment]
The DB was created, but the failing pod logs say "Error: DATABASE_URL environment variable is required"

**Comment by nottrobin** [comment]
Okay so presumably the secret is not being replaced correctly. It's there in the configs: https://github.com/canonical-web-and-design/partners.ubuntu.com/blob/test-demo/deploy/site.yaml#L12

**Comment by jpmartinspt** [comment]
Yep, I think it's because for partners the DB secret is only defined inside `production` and `staging`. Because we do `konf demo site.yaml` there isn't actually anything for the script to replace. If we add the env definition to top level too it should get the demo working.

**Comment by nottrobin** [comment]
@jpmartinspt oh. I was actually creating this as a proposal for the standard pattern for sites with databases. I like it because:

- It collects DB secrets together in the same way we collect `secret-keys` together
- It makes it clear that staging connects to a different database from production

If `konf demo site.yaml` is looking for a specific `demo` environment section then it sounds like it's almost encouraging us to create that section and put something specific in it, which I think is very much what we *don't* want.

I guess the demo config should probably use the `staging` config as its template. I'll see if I can file a PR to achieve this.
