### ISSUE TITLE
“Start demo” doesn’t let me start a demo

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-web-and-design/demos.haus#19]
1\. Go to [demos.haus](https://demos.haus/)
2\. Choose “Start a demo”

What happens: You end up on [a Jenkins page](https://jenkins.canonical.com/webteam/view/demos/job/start-demo/) with no ability to start a demo.

What should happen: A form prompts you for a PR number or URL to start a demo.

**Comment by anthonydillon** [comment]
This is poorly announced and I will send an email to address this soon. 

For now, 
1. Once on the Jenkins page, you should log in.
2. Click in the "Build with Parameters" link on the side navigation
3. Enter the URL of the PR and click "Build"
4. The output should end with a link to the demo

**Comment by anthonydillon** [comment]
The guide is written and published: https://discourse.ubuntu.com/t/building-a-demo-from-a-pr/18926.

**Comment by matthewpaulthomas** [comment]
I appreciate the effort, but it would not have occurred to me that I needed to read a guide to achieve this. Let alone a guide on a completely separate Web site! On the previous demo service, it was self-evident.

I think a simpler solution would be to change the “Start a demo” link to point to https://jenkins.canonical.com/webteam/securityRealm/commenceLogin?from=%2Fwebteam%2Fview%2Fdemos%2Fjob%2Fstart-demo%2Fbuild. That way you don’t need to do steps 1 or 2, and step 3 becomes self-evident.

**Comment by anthonydillon** [comment]
Your right, let's do this.
