### ISSUE TITLE
Demo is building.... after it's finished building

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/demos.haus#21]
Sometimes the "demo is building..." image gets stuck even after the real image has completed building. This appears to happen randomly across projects and the weirdest thing is that it will sometimes just start working hours later.

**Comment by SirSamTumless** [comment]
@jpmartinspt could you give this a prior then triage it?

**Comment by jpmartinspt** [comment]
@hatched I suspect this is due to browsers caching the page, some people have come to me with the same issue `CTRL+SHIFT+R` fixes it. This could not be true if the deployment failed, since the jenkins job is not waiting for k8s to succeed (needs fixing) and k8s would just keep serving the `demo is building` site as a fallback. This makes me wonder if the `bulding` page is useful at all? Maybe it´s fine if we don't show anything until the demo is built.

**Comment by jpmartinspt** [comment]
Not having the `buidling` page would also resolve https://github.com/canonical-web-and-design/demos.haus/issues/17

**Comment by hatched** [comment]
If it were to act more as a status page then I think it would be more helpful....so have progress and an indication if it failed, but right now it's usefulness is questionable. I'd be +1 with removing it unless you had the time to implement it as a status view.

**Comment by hatched** [comment]
I've ran into this again today where the jobs finished building but it didn't switch the image over. It might be worth a try to just remove that swap and see if the issue goes away.

**Comment by anthonydillon** [comment]
Sorry I had to stop a dashboard demo start today as we wanted to get the homepage back for Ubuntu.com. That could have been the one. 

The build had been running for over 6 mins and was being up the demo requests.

**Comment by hatched** [comment]
Oh haha ok :D

**Comment by jkfran** [comment]
I think many of these issues are reduced after the memory changes on Konf. I spoke today with Joao about considering having a docker image for failed demos so people can know if their demo is building or not.

**Comment by jpmartinspt** [comment]
I changed the page a bit, and it know gives you the link to the actual job that is/failed building the demo. On top of that the jenkins job now waits for the deployment to succeed, so if something is wrong at the k8s level the job should have a failed status.
